apiVersion: v1
kind: Service
metadata:
  namespace: fluxv2-production
  name: spring-petclinic-plain
  labels:
    app: spring-petclinic-plain
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9096
      targetPort: http
  selector:
    app: spring-petclinic-plain