apiVersion: v1
kind: Service
metadata:
  namespace: argocd-staging
  name: spring-petclinic-plain
  labels:
    app: spring-petclinic-plain
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 9020
      targetPort: http
  selector:
    app: spring-petclinic-plain
