extraEnv: |
  - name: TZ
    value: Europe/Berlin

service:
  type: ClusterIP

ingress:
  enabled: <#if config.features.exampleApps.petclinic.baseDomain?has_content>true<#else>false</#if>


<#if config.application.openshift == true>
securityContext:
  runAsUser: null
  runAsGroup: null
</#if>  

<#if config.application.podResources == true>
resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 650Mi
<#else>
<#-- Explicitly set to null, because the chart sets memory by default
     https://github.com/cloudogu/spring-boot-helm-chart/blob/0.3.2/values.yaml#L40 -->
resources: null
</#if>
