<#assign DockerImageParser=statics['com.cloudogu.gitops.utils.DockerImageParser']>
<#if config.content.variables.images.nginx?has_content>
<#assign nginxImageObject = DockerImageParser.parse(config.content.variables.images.nginx)>
image:
  registry: ${nginxImageObject.registry}
  repository: ${nginxImageObject.repository}
  tag: ${nginxImageObject.tag}
<#else>
image:
  repository: bitnamilegacy/nginx
</#if>
<#if config.registry.createImagePullSecrets == true>

global:
  imagePullSecrets:
    - proxy-registry
</#if>
service:
  ports:
    http: 80
  type: ClusterIP
# We don't use staticSiteConfigmap, so this is extensible for our secret example. See ArgoCD.groovy
extraVolumes:
  - name: index
    configMap:
      name: index-nginx
      items:
        - key: index.html
          path: index.html
  <#if config.features.secrets.active>
  - name: secret
    secret:
      secretName: nginx-helm-jenkins
      items:
        - key: some-secret
          path: index.html
  </#if>
extraVolumeMounts: 
  - name: index
    mountPath: /app
    readOnly: true
  <#if config.features.secrets.active>
  - name: secret
    mountPath: /app/secret
    readOnly: true
  </#if>

<#if config.application.podResources == true>
resources:
  limits:
    cpu: 1
    memory: 30Mi
  requests:
    cpu: 300m
    memory: 15Mi
</#if>