## Server
server:
  ## Server service configuration
  service:
    type: LoadBalancer
    servicePortHttp: 9092
    servicePortHttps: 9093

  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  config:
    repositories: |
      - url: http://scmm-scm-manager.default.svc.cluster.local:9091/scm/repo/argocd/gitops
        passwordSecret:
          name: gitops-scmm
          key: PASSWORD
        usernameSecret:
          name: gitops-scmm
          key: USERNAME
      - url: http://scmm-scm-manager.default.svc.cluster.local:9091/scm/repo/argocd/nginx-helm
        passwordSecret:
          name: gitops-scmm
          key: PASSWORD
        usernameSecret:
          name: gitops-scmm
          key: USERNAME
      - type: helm
        url: https://charts.bitnami.com/bitnami
        name: bitnami
