apiVersion: v1
kind: Secret
metadata:
  name: secret-2-sample
  namespace: fluxv1-staging
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/service-account-token
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  extra: YmFyCg==