content:
  repos:
    - url: https://github.com/cloudogu/gitops-build-lib
      target: 3rd-party-dependencies/gitops-build-lib
      overwriteMode: RESET
    - url: https://github.com/cloudogu/ces-build-lib
      target: 3rd-party-dependencies/ces-build-lib
      overwriteMode: RESET
    - url: https://github.com/cloudogu/spring-boot-helm-chart
      target: 3rd-party-dependencies/spring-boot-helm-chart
      overwriteMode: RESET
    - url: https://github.com/cloudogu/spring-petclinic
      target: argocd/petclinic-plain
      ref: feature/gitops_ready
      targetRef: main
      overwriteMode: UPGRADE
      createJenkinsJob: true
    - url: https://github.com/cloudogu/spring-petclinic
      target: argocd/petclinic-helm
      ref: feature/gitops_ready
      targetRef: main
      overwriteMode: UPGRADE
      createJenkinsJob: true
    - url: https://github.com/cloudogu/gitops-playground
      path: examples/example-apps-via-content-loader/
      ref: feature/remove-cli-param-remote
      templating: true
      type: FOLDER_BASED
      overwriteMode: UPGRADE

  namespaces:
    - ${config.application.namePrefix}example-apps-production
    - ${config.application.namePrefix}example-apps-staging
  variables:
    petclinic:
      baseDomain: "petclinic.localhost"
    nginx:
      baseDomain: "nginx.localhost"
    images:
      kubectl: "bitnamilegacy/kubectl:1.29"
      helm: "ghcr.io/cloudogu/helm:3.16.4-1"
      kubeval: "ghcr.io/cloudogu/helm:3.16.4-1"
      helmKubeval: "ghcr.io/cloudogu/helm:3.16.4-1"
      yamllint: "cytopia/yamllint:1.25-0.7"
      nginx: ""
      petclinic: "eclipse-temurin:17-jre-alpine"
      maven: ""