apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-production
  namespace: argocd
#  annotations:
##  only this application in this project is going to be notified about when this events triggers
#    notifications.argoproj.io/subscribe.on-health-degraded.email: argocd@testeroony.de
spec:
  destination:
    namespace: argocd-production
    server: https://kubernetes.default.svc
  project: nginx
  source:
    path: production/nginx
    repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/gitops
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
